//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp_Gluhhov
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mudel_kutsekool_gluhhovContainer : DbContext
    {
        public mudel_kutsekool_gluhhovContainer()
            : base("name=mudel_kutsekool_gluhhovContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Opilane> Opilanes { get; set; }
        public virtual DbSet<Ryhm> Ryhms { get; set; }
    }
}
