//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp_Gluhhov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ryhm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ryhm()
        {
            this.Opilanes = new HashSet<Opilane>();
        }
    
        public int ryhmid { get; set; }
        public string ryhmnimi { get; set; }
        public string osakond { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opilane> Opilanes { get; set; }
    }
}
